# Setup

In [ ]:
!pip install openai==0.28

In [ ]:
import openai
import numpy as np

In [ ]:
# Key that gives an access to openai account
openai.api_key = 'key_code'

input text

In [ ]:
text = """
The company sells a number of different furniture products. These products are grouped into several product lines the identifier for a product is Product_ID, while the identifier for a product line is Product_Line_ID.  Referring to the customer invoice, we identify the following additional attributes for products: Product_Description, Product_Finish, and Unit_Price. Another attribute for product line is Product_Line_name. A product line may group any number of products, but must group at least one product. Each product must belong to exactly one product line. Customers submit orders for products. The identifier for an order is Order-ID, and another attribute is Order-Date. A customer may submit any number of orders, but need not submit any orders. Each order is submitted by exactly one customer. The identifier for a customer is Customer_ID. Other attributes include Customer_name and Customer_Address. A given customer order but request at least one product. Any product sold by Pine Valley Furniture may not be requested on any order, or or may be requested on one or more orders. An attribute associated with each order and product is Quantity, which is the number of units requested. Pine Valley Furniture has established sales territories for its customers. Each customer does business in one or more of these sales territories. The identifier for a sales territory is Territory_ID. A sales territory may have any number of customers, or may not have any customers doing business. Pine Valley Furniture Company has several salespersons. The identifier for a salesperson is Salesperson_ID. Other attributes include Salesperson_Name, Salesperson_Telephone, and Salesperson_Fax. A salesperson serves exactly one sales territory. Each sales territory is served by one or more salespersons. Each product is assembled from one or more raw materials. The identifier for the raw material entity is Material_ID other attributes include Unit_of_Measure and Unit_Price. Each raw material. May be assembled into one or more products. Raw materials are supplied by vendors. The identifier for a vendor is Vendor_ID. Other attributes include Vendor_Name and Vendor_Address. Each raw material can be suppled by one or more vendors. A vendor may supply any number of raw materials, or may not supply any raw materials to Pine Valley Furniture. An attribute of the relationship between vendor and raw material is Unit_Price. Pine Valley Furniture has established a number of work centers. The identifier for a work center is Work_Center_ID. Another attribute is Location. Each product is produced in one or more work centers. A work center may be used to produce any number of products, or may not be used to produce any products. The company has over 100 employees. The identifier for employee is Employee_ID. Other attributes are Employee_Name, EmployeeAddress, and Skill.  An employee may have more than one skill. A skill can be mastered by many employees. Each employee works in one or more work centers. A work center must have at least one employee working in that center, but may have any number of employees. Each employee has exactly one supervisor. An employee who is a supervisor may supervise any number of employees, but not all employees are supervisors.
"""

## Prompt tentatives

few-shot prompting examples

In [ ]:
# parameter controlling randomness of the output
temp = 0.0

def get_completion(prompt, model="gpt-4"):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temp, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]

In [ ]:
def gpt_output():
  answers = []
  for i in range(1):
      response = get_completion(prompt)
      answers.append(response)

  return answers[0]

Prompt 1 - one-shot prompting

bad example since additional attributes are inserted in the output which are not present in the input text

In [ ]:
ex = """
A set of artists that are characterised by the name, status (active/stopped performing), their website and their multiple phone numbers.
Moreover, for each artist we should store the year when they started performing and the year when they have stopped
(if not active at the moment). Artists are associated with countries where they were/are based.
Each artist has a set of releases: albums, singles or EPs. Each release should store information about the number of featured songs.
We must not forget that songs can be a result of collaboration between artists. Songs should store a title, duration and a number of plays.
Additionally, we should keep record of links that point to where the songs are stored on a server.
We are supposed to display to users top-charts of songs in different countries. Moreover, we want to store information on upcoming concerts.
The concerts are associated with the countries where they take place.
The users should also be able to see the date, city, address, and the name of the venue.
The concerts typically can involve multiple artists. For each user we should keep track of a username, email, and the user’s country.
The users should be able to create playlists from a number of songs. A playlist is considered to be active if it is played more than once in a month.
The users can follow artists as well as other users. It is also possible for a user to add other users’ playlists to the list of her/his own playlists.
There are also a set of subscriptions that users can purchase.
They differ in a number of playlists that can be created and the possibility to download tracks to a device for the offline playback.
Subscriptions are priced differently depending on the country a user resides in. At a moment of time, a user can have only one type of subscription.
"""

output = """
ent_attr (containing the entities as keys and the attributes as values):
{‘artist’: [‘start year’, ‘end year’, ‘name’, ‘status’, ‘website’, ‘ID’], ‘release’: [‘ID’, ‘number of featured songs’], ‘song’: [‘title’, ‘duration’, ‘number of plays’, ‘link’, ‘ID’], ‘playlist’: [‘status’, ‘last play’, ‘name’, ‘ID’], ‘top-chart’: [‘ID’], ‘country’: [‘name’], ‘concert’: [‘date’, ‘city’, ‘address’, ‘name’, ‘ID’], ‘subscription’: [‘ID’, ‘download’, ‘number of playlist’], ‘user’: [‘ID’, ‘username’, ‘email’]}
Cardinality (containing the cardinality and the entities of the relationship):
[[(0:N), ‘artist’, ‘user’], [(0:N), ‘user’, ‘artist’], [(1:N),‘artist’, ‘release’], [(1:N)‘release’, ‘artist’], [(1:N),‘artist’, ‘song’], [(1:N),‘song’, ‘artist’], [(1:N),‘artist’, ‘country’], [(0:N)‘country’,’artist’], [(0:N),‘artist’, ‘concert’], [(1:N),‘concert’, ‘artist’], [(1:N),‘release’, ‘song’], [(1:N),‘song’,’release’], [(0:N),‘song’, ‘playlist’], [(1:N),‘playlist’, ‘song’], [(0:N),‘song’, ‘top-chart’], [(1:N),‘top-chart’, ‘song’], [(0:N),‘playlist’, ‘user’], [(0:N),‘user’, ‘playlist’], [(1:1),‘playlist’, ‘user’], [(0:N),‘user’, ‘playlist’], [(1:1),‘top-chart’, ‘country’], [(1:1),‘country’, ‘top-chart’], [(0:N),‘country’, ‘concert’], [(1:1),‘concert’, ‘country’], [(0:N),‘country’, ‘subscription’], [(1:N),‘subscription’, ‘country’], [(0:N),‘country’, ‘user’], [(1:1),‘user’, ‘country’], [(0:N),‘user’, ‘user’], [(0:N),‘user’, ‘user’], [(1:1),‘user’, ‘subscription’], [(0:N),‘subscription’, ‘user’]]
cardinality_attr (containing the entities and their unique attributes):
[[1, ‘artist’,’ID’], [2, 'artist', 'phone number'],[1, ‘release’,’ID’], [1,’song’, ‘ID’], [1, ‘playlist’,’ID’], [1,’top-chart’,’ID’], [1,’country’,’name’], [1,’concert’,’ID],[1,’user’,’ID’],[1,’subscription’,’ID’]]
"""

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and the cardinality for each relationship
(cardinality in both directions of the relationship).
An example of the task required is given below, where the 'input text' is the original text and the 'output' are the elements for the entity-relationship diagram:

Input text:
'
{ex}
'

Output:
'
{output}
'
Given the text in the triple backticks, extract the required elements for the build of an ER-diagram:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

Prompt 2 - zero-shot prompting

the structure of the output passed is too complex and introduce some errors

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and the cardinality for each relationship
(cardinality in both directions of the relationship).
You need to create two dictionaries and two arrays for each type of element you have to extract, for a total of 4 structure :
1. A dictionary named 'ent_attr' containing as keys all the entities extracted from the input text and as values of each key an array containing all the attributes associated to that entity. For example: {{'person':['id', 'name'], 'teacher':['age']}}
2. A dictionary named 'composite_attr' containing as key the entity the composite attribute belongs to, and as values an array made of at least two elements for each entity; the first element is the composite attribute, and the following elements are all the simple attributes which compose the composite attribute. For example: {{'person':['name', 'first name', 'last name']}}
3. An array named 'cardinality' where each elements contains 4 data: the first one is a tuple containing the cardinality of the relationship (the quantity of the first entity followed by the quantity of the second entity), the second data is the first entity of the relationship, the third data the second entity, and the last data is the verb of the relationship. The types of the cardinality data can be 1 (exactly one), 01 (zero or one), 02 (zero or more), 12 (one or more). e.g. [[(1, 1), 'person', 'car', 'own')]].
4. An array named 'cardinality_attr' containing the special attributes (unique and multivalued attributes). Each element contains 3 data: the first one is the type of attribue (1 for unique attributes, 2 for multivalued attributes), the second data is the entity associated to that attribute, and the third data is the unique or multivalued attribute. E.g. [[1, 'user', 'code'], [2, 'person', 'phone number']].
All that is put in these arrays or dictionaries should be set to its singular form. If in the text there are not both the two cardinalities for each relationship among two entities, try to figure out the cardinality by intuition analyzing the entities involved.
Print in order the ent_attr, composite_attr, cardinality and cardinality_attr filled with the data you have been able to extract.
The input text from which you have to extract the elements for the Entity-Relastionship Diagram is given below in the triple backticks:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

Prompt 3 - zero-shot prompting

better but need to fix the cardinalities including the zero (zero or more, zero or one)

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and the cardinality for each relationship
(cardinality in both directions of the relationship). Given the text in the triple backticks, extract the required elements for the build of an ER-diagram:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

Prompt 5 - okay but can be better for the zeros in the cardinality

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and the cardinality for each relationship
(one-to-many, many-to-many and specify trying to understand by the entities if the zero is included even if it is not written). Given the text in the triple backticks, extract the required elements for the build of an ER-diagram:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

Entity Types: Company, Furniture Products, Product Lines, Customer Invoice, Customers, Orders, Sales Territories, Salespersons, Raw Materials, Vendors, Work Centers, Employees, Supervisors.

Attributes: 
- Furniture Products: Product_ID, Product_Description, Product_Finish, Unit_Price.
- Product Lines: Product_Line_ID, Product_Line_name.
- Customer Invoice: Product_ID, Product_Description, Product_Finish, Unit_Price.
- Customers: Customer_ID, Customer_name, Customer_Address.
- Orders: Order-ID, Order-Date, Quantity.
- Sales Territories: Territory_ID.
- Salespersons: Salesperson_ID, Salesperson_Name, Salesperson_Telephone, Salesperson_Fax.
- Raw Materials: Material_ID, Unit_of_Measure, Unit_Price.
- Vendors: Vendor_ID, Vendor_Name, Vendor_Address, Unit_Price.
- Work Centers: Work_Center_ID, Location.
- Employees: Employee_ID, Employee_Name, EmployeeAddress, Skill.

Unique Attributes: 
- Furniture Products: Product_ID.
- Product Lines: Product_Line_ID.
- Customers: Customer_ID.
- Orders:

[[3, 0, 0],
 [1, 2, 2],
 [5, 8, 2],
 [2, 1, 2],
 [2, 1, 2],
 [2, 1, 0],
 [6, 0, 0],
 [1, 2, 1],
 [3, 4, 1],
 [4, 0, 0]]

Prompt 6 - okay, seems the best since can understand when the zeros should be included in cardinalities

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and cardinalities (01, 1, 0N, N), where 01 is 'zero or one', 1 is 'exactly one', 0N is 'zero or more' and N is 'one or more'.
Given the text in the triple backticks, extract the required elements for the build of an ER-diagram:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

Prompt 7 - okay

In [ ]:
requirements = f"""
{text}
"""

prompt = f"""
The task is to extract elements for creating an Entity-Relationship Diagram from a given natural language text.
These elements should be: entity types, attributes, unique attributes (which identify each entity of an entity type),
multivalued attributes, composite attributes, relationship between entities and cardinalities (01, 1, 0N, N), where 01 is 'zero or one', 1 is 'exactly one', 0N is 'zero or more' and N is 'one or more'.
Attention to not create entity types which doesn't exist (if you are not certain about the entity, don't output it). Given the text in the triple backticks, extract the required elements for the build of an ER-diagram:


Text:
```{requirements}```
"""

In [ ]:
input_text = gpt_output()
print(input_text)

## Prompts evaluation with training set
For the evaluation we take into consideration only the best ones which are the prompts number 5,6 and 7 and we evaluate them only using entity types and attributes

In [ ]:
# array for each prompt where each element contains true positives, false positives and false negatives
prompt5 = [[47, 12, 13], [7,11,0], [33,0,0], [30,2,0], [16,4,1], [8,2,0], [12,17,3], [14,5,0], [7,11,0], [28,8,1], [18,1,1], [27,0,0], [13,2,3], [10,1,1], [34,1,0], [6,4,0], [19,2,0], [25,11,5], [10,0,0]]
prompt5_1 = [[47, 12, 13], [15,3,0], [33,0,0], [30,2,0], [16,4,1],[8,2,0], [14,15,4], [19,0,0], [15,3,0], [28,8,1], [18,1,1], [27,0,0], [13,2,3], [10,1,1], [34,1,0], [6,4,0], [19,2,0], [25,11,5], [10,0,0]]
prompt6 = [[40,15,22], [7, 0, 0], [33,0,0], [30,0,0],[16,4,1], [8,2,0], [13,17,3], [14,6,0], [7,10,0], [28,8,1], [18,1,1], [27,0,0], [14,1,2], [10,0,0], [34,1,0], [6,3,0], [19,2,0], [23,4,10], [10,0,0]]
prompt7 = [[40, 21, 22], [7,0,0], [33,0,0], [30,0,0], [16,4,1], [8,7,0], [10,17,4], [14,6,0], [7,10,0], [30,12,0], [18,1,1], [27,0,0], [13,2,2], [10,0,0], [34,1,0], [6,4,0], [19,2,0], [23,9,9], [10,0,0]]

average training set

In [ ]:
np_prompt5 = np.array(prompt5)
np_prompt5_1 = np.array(prompt5_1)
np_prompt6 = np.array(prompt6)
np_prompt7 = np.array(prompt7)


sum_prompt5 = np.sum(np_prompt5, axis=0)
sum_prompt5_1 = np.sum(np_prompt5_1, axis=0)
sum_prompt6 = np.sum(np_prompt6, axis=0)
sum_prompt7 = np.sum(np_prompt7, axis=0)

# print sum of true positives, false positives and false negatives for each main prompt
print('tp, fp, fn prompt 5:',sum_prompt5)
print('tp, fp, fn prompt 5, evaluation 1:',sum_prompt5_1)
print('tp, fp, fn prompt 6:',sum_prompt6)
print('tp, fp, fn prompt 7:',sum_prompt7)

[364  94  28]
[387  71  29]
[357  74  40]
[355  96  39]


Functions for precision, recall and F1 score

In [ ]:
def precision(tp, fp):
  if tp + fp == 0:
    return 0
  else:
    return tp/(tp + fp)

In [ ]:
def recall(tp, fn):
  if tp + fn == 0:
    return 0
  else:
    return tp/(tp + fn)

In [ ]:
def f1(precision,recall):
  if precision + recall == 0:
    return 0
  else:
    return 2 * ((precision * recall) / (precision + recall))

prompt 5

precision, recall and F1 score

In [ ]:
prec5 = precision(sum_prompt5[0], sum_prompt5[1])
rec5 = recall(sum_prompt5[0], sum_prompt5[2])
f1_5 = f1(prec5, rec5)

print('precision:',prec5)
print('recall:'rec5)
print('F1 score:'f1_5)

0.7947598253275109
0.9285714285714286
0.856470588235294


Prompt 5.1

precision, recall and F1 score

In [ ]:
prec5_1 = precision(sum_prompt5_1[0], sum_prompt5_1[1])
rec5_1 = recall(sum_prompt5_1[0], sum_prompt5_1[2])
f1_5_1 = f1(prec5_1, rec5_1)

print('precision:',prec5_1)
print('recall:'rec5_1)
print('F1 score:'f1_5_1)

0.8449781659388647
0.9302884615384616
0.88558352402746


Prompt 6

precision, recall and F1 score

In [ ]:
prec6 = precision(sum_prompt6[0], sum_prompt6[1])
rec6 = recall(sum_prompt6[0], sum_prompt6[2])
f1_6 = f1(prec6, rec6)

print('precision:',prec6)
print('recall:'rec6)
print('F1 score:'f1_6)

0.8283062645011601
0.8992443324937027
0.8623188405797101


Prompt 7

precision, recall and F1 score

In [ ]:
prec7 = precision(sum_prompt7[0], sum_prompt7[1])
rec7 = recall(sum_prompt7[0], sum_prompt7[2])
f1_7 = f1(prec7, rec7)

print('precision:',prec7)
print('recall:'rec7)
print('F1 score:'f1_7)

0.7871396895787139
0.9010152284263959
0.8402366863905325


## Best prompt (5.1) evaluation with test set

In [ ]:
best_prompt = [[12,0,0], [27,2,0], [31,11,4], [33,4,2], [18,0,0], [29,6,2], [27,1,1], [41,1,0], [35,6,1], [13,0,1], [54,9,7]]

In [ ]:
best_np_prompt = np.array(best_prompt)
sum_best_prompt = np.sum(best_np_prompt, axis=0)
print('tp, fp and fn:',sum_best_prompt)

[320  40  18]


In [ ]:
best_prec = precision(sum_best_prompt[0], sum_best_prompt[1])
best_rec = recall(sum_best_prompt[0], sum_best_prompt[2])
best_f1 = f1(best_prec, best_rec)

print('precision:',best_prec)
print('recall:',best_rec)
print('F1 score:',best_f1)

0.8888888888888888
0.9467455621301775
0.9169054441260744


## Best prompt (5.1) evaluation with training set

In [ ]:
best_prompt_train = [[48,12,8], [34,1,0], [28,9,2], [26,4,6], [27,0,0],[12,1,3], [32,10,1], [18,1,1], [19,1,0],[32,1,1],[16,3,1], [30,0,0],[19,3,0],[14,18,5],[15,3,0], [20,6,0], [17,0,0],[6,2,0],[11,0,0],[9,0,0],[15,3,0]]

In [ ]:
best_np_prompt_train = np.array(best_prompt_train)
sum_best_prompt_train = np.sum(best_np_prompt_train, axis=0)
print('tp, fp and fn:', sum_best_prompt_train)

[448  78  28]


In [ ]:
best_prec_train = precision(sum_best_prompt_train[0], sum_best_prompt_train[1])
best_rec_train = recall(sum_best_prompt_train[0], sum_best_prompt_train[2])
best_f1_train = f1(best_prec_train, best_rec_train)

print('precision:',best_prec_train)
print('recall:',best_rec_train)
print('F1 score:'best_f1_train)

0.8517110266159695
0.9411764705882353
0.8942115768463074


## Best prompt (5.1) separated evaluation with training set
Split results of elements for each dataset.
For the training set only entities and attributes should be taken into consideration

In [ ]:
# training set

ent = [[5,2,0], [9,0,0],[6,0,0], [5,1,0], [4,2,0], [3,0,0], [3,0,0],[3,0,0], [3,2,0], [5,0,0], [3,2,0], [3,0,0], [4,0,0], [3,0,0], [4,0,0],[2,0,0], [3,1,0], [1,1,0],[2,0,0],[4,0,0]]
attr = [[15,5,0], [22,4,4], [17,1,0], [13,2,3], [16,1,0], [10,1,0], [10,1,0], [9,1,0], [7,6,2], [15,0,0], [3,8,0], [9,0,0], [4,3,0], [8,0,0], [16,0,0],[5,0,0],[7,0,0],[3,1,0],[4,0,0],[4,3,0]]
unique = [[4,0,0], [6,3,3], [6,0,0], [4,2,0], [5,1,1], [3,0,0], [3,0,0],[3,0,0], [2,3,1],[5,0,0], [3,2,0], [5,0,0], [4,0,0], [3,0,0],[4,0,0],[2,0,0],[2,0,0],[1,0,0],[2,0,0],[4,0,0]]
composite = [[0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0],[0,0,0], [0,0,0],[0,0,0], [0,0,0], [0,0,0], [0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[3,0,0],[0,0,0]]
multivalued = [[0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,1,0], [0,0,0], [0,1,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0], [0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]
relation = [[4,4,1], [11,1,5], [5,0,0], [4,0,2], [5,1,0], [2,0,0], [3,0,0],[1,2,1], [2,3,2], [5,0,0], [5,0,0], [2,0,0], [3,0,0],[3,0,0], [3,0,0],[1,0,0],[1,2,2],[1,1,0],[1,0,0],[3,0,0]]

In [ ]:
ent_np_prompt_train = np.array(ent)
attr_np_prompt_train = np.array(attr)
unique_np_prompt_train = np.array(unique)
composite_np_prompt_train = np.array(composite)
multivalued_np_prompt_train = np.array(multivalued)
relation_np_prompt_train = np.array(relation)

sum_ent_prompt_train = np.sum(ent_np_prompt_train, axis=0)
sum_attr_prompt_train = np.sum(attr_np_prompt_train, axis=0)
sum_unique_prompt_train = np.sum(unique_np_prompt_train, axis=0)
sum_composite_prompt_train = np.sum(composite_np_prompt_train, axis=0)
sum_multivalued_prompt_train = np.sum(multivalued_np_prompt_train, axis=0)
sum_relation_prompt_train = np.sum(relation_np_prompt_train, axis=0)

print('ent tp, fp and fn:',sum_ent_prompt_train)
print('attr tp, fp and fn:',sum_attr_prompt_train)
print('unique tp, fp and fn:',sum_unique_prompt_train)
print('composite tp, fp and fn:',sum_composite_prompt_train)
print('multivalued tp, fp and fn:',sum_multivalued_prompt_train)
print('relationships tp, fp and fn:',sum_relation_prompt_train)

ent: [75 11  0]
attr: [197  37   9]
unique: [71 11  5]
composite: [3 0 0]
multivalued: [0 2 0]
relationships: [65 14 13]


In [ ]:
ent_prec_train = precision(sum_ent_prompt_train[0], sum_ent_prompt_train[1])
ent_rec_train = recall(sum_ent_prompt_train[0], sum_ent_prompt_train[2])
ent_f1_train = f1(ent_prec_train, ent_rec_train)

print('ent precision, recall and F1 score:', ent_prec_train, ent_rec_train, ent_f1_train)

attr_prec_train = precision(sum_attr_prompt_train[0], sum_attr_prompt_train[1])
attr_rec_train = recall(sum_attr_prompt_train[0], sum_attr_prompt_train[2])
attr_f1_train = f1(attr_prec_train, attr_rec_train)

print('attr precision, recall and F1 score:', attr_prec_train, attr_rec_train, attr_f1_train)

unique_prec_train = precision(sum_unique_prompt_train[0], sum_unique_prompt_train[1])
unique_rec_train = recall(sum_unique_prompt_train[0], sum_unique_prompt_train[2])
unique_f1_train = f1(unique_prec_train, unique_rec_train)

print('unique precision, recall and F1 score:', unique_prec_train, unique_rec_train, unique_f1_train)

composite_prec_train = precision(sum_composite_prompt_train[0], sum_composite_prompt_train[1])
composite_rec_train = recall(sum_composite_prompt_train[0], sum_composite_prompt_train[2])
composite_f1_train = f1(composite_prec_train, composite_rec_train)

print('composite precision, recall and F1 score:', composite_prec_train, composite_rec_train, composite_f1_train)

multivalued_prec_train = precision(sum_multivalued_prompt_train[0], sum_multivalued_prompt_train[1])
multivalued_rec_train = recall(sum_multivalued_prompt_train[0], sum_multivalued_prompt_train[2])
multivalued_f1_train = f1(multivalued_prec_train, multivalued_rec_train)

print('multivalued precision, recall and F1 score:', multivalued_prec_train, multivalued_rec_train, multivalued_f1_train)

relation_prec_train = precision(sum_relation_prompt_train[0], sum_relation_prompt_train[1])
relation_rec_train = recall(sum_relation_prompt_train[0], sum_relation_prompt_train[2])
relation_f1_train = f1(relation_prec_train, relation_rec_train)

print('relation precision, recall and F1 score:', relation_prec_train, relation_rec_train, relation_f1_train)

ent: 0.872093023255814 1.0 0.9316770186335404
attr: 0.8418803418803419 0.9563106796116505 0.8954545454545455
unique: 0.8658536585365854 0.9342105263157895 0.8987341772151899
composite: 1.0 1.0 1.0
multivalued: 0.0 0 0
relation: 0.8227848101265823 0.8333333333333334 0.8280254777070064


## Best prompt (5.1) separated evaluation with test set

In [ ]:
# test set

ent = [[3,0,0], [4,1,0],[6,2,0],[5,1,0],[4,1,0],[3,0,0],[5,0,0],[4,0,0],[4,1,0],[5,0,0],[10,3,1]]
attr = [[3,3,0],[16,0,0],[20,3,5],[18,0,0],[19,1,1],[10,0,0],[31,0,0],[16,0,0],[15,4,0],[4,0,0],[23,7,6]]
unique = [[3,0,0],[4,0,0],[4,0,0],[4,0,0],[4,0,0],[3,0,0],[5,0,0],[4,0,0],[4,0,0],[4,0,0],[8,0,2]]
composite = [[0,0,0],[0,0,0],[4,0,0],[0,0,0],[0,1,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0], [0,0,0]]
multivalued = [[0,0,0],[0,0,0],[0,3,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[1,0,0], [0,0,0],[0,1,0]]
relation = [[3,0,0],[1,2,2],[5,8,2],[2,1,2],[2,1,2],[2,1,0],[6,0,0],[1,2,1],[3,4,1], [4,0,0],[8,1,3]]

In [ ]:
ent_np_prompt_train = np.array(ent)
attr_np_prompt_train = np.array(attr)
unique_np_prompt_train = np.array(unique)
composite_np_prompt_train = np.array(composite)
multivalued_np_prompt_train = np.array(multivalued)
relation_np_prompt_train = np.array(relation)

sum_ent_prompt_train = np.sum(ent_np_prompt_train, axis=0)
sum_attr_prompt_train = np.sum(attr_np_prompt_train, axis=0)
sum_unique_prompt_train = np.sum(unique_np_prompt_train, axis=0)
sum_composite_prompt_train = np.sum(composite_np_prompt_train, axis=0)
sum_multivalued_prompt_train = np.sum(multivalued_np_prompt_train, axis=0)
sum_relation_prompt_train = np.sum(relation_np_prompt_train, axis=0)

print('ent tp, fp and fn:',sum_ent_prompt_train)
print('attr tp, fp and fn:',sum_attr_prompt_train)
print('unique tp, fp and fn:',sum_unique_prompt_train)
print('composite tp, fp and fn:',sum_composite_prompt_train)
print('multivalued tp, fp and fn:',sum_multivalued_prompt_train)
print('relationships tp, fp and fn:',sum_relation_prompt_train)

ent: [53  9  1]
attr: [175  18  12]
unique: [47  0  2]
composite: [4 1 0]
multivalued: [1 4 0]
relationships: [37 20 13]


In [ ]:
ent_prec_train = precision(sum_ent_prompt_train[0], sum_ent_prompt_train[1])
ent_rec_train = recall(sum_ent_prompt_train[0], sum_ent_prompt_train[2])
ent_f1_train = f1(ent_prec_train, ent_rec_train)

print('ent precision, recall and F1 score:', ent_prec_train, ent_rec_train, ent_f1_train)

attr_prec_train = precision(sum_attr_prompt_train[0], sum_attr_prompt_train[1])
attr_rec_train = recall(sum_attr_prompt_train[0], sum_attr_prompt_train[2])
attr_f1_train = f1(attr_prec_train, attr_rec_train)

print('attr precision, recall and F1 score:', attr_prec_train, attr_rec_train, attr_f1_train)

unique_prec_train = precision(sum_unique_prompt_train[0], sum_unique_prompt_train[1])
unique_rec_train = recall(sum_unique_prompt_train[0], sum_unique_prompt_train[2])
unique_f1_train = f1(unique_prec_train, unique_rec_train)

print('unique precision, recall and F1 score:', unique_prec_train, unique_rec_train, unique_f1_train)

composite_prec_train = precision(sum_composite_prompt_train[0], sum_composite_prompt_train[1])
composite_rec_train = recall(sum_composite_prompt_train[0], sum_composite_prompt_train[2])
composite_f1_train = f1(composite_prec_train, composite_rec_train)

print('composite precision, recall and F1 score:', composite_prec_train, composite_rec_train, composite_f1_train)

multivalued_prec_train = precision(sum_multivalued_prompt_train[0], sum_multivalued_prompt_train[1])
multivalued_rec_train = recall(sum_multivalued_prompt_train[0], sum_multivalued_prompt_train[2])
multivalued_f1_train = f1(multivalued_prec_train, multivalued_rec_train)

print('multivalued precision, recall and F1 score:', multivalued_prec_train, multivalued_rec_train, multivalued_f1_train)

relation_prec_train = precision(sum_relation_prompt_train[0], sum_relation_prompt_train[1])
relation_rec_train = recall(sum_relation_prompt_train[0], sum_relation_prompt_train[2])
relation_f1_train = f1(relation_prec_train, relation_rec_train)

print('relation precision, recall and F1 score:', relation_prec_train, relation_rec_train, relation_f1_train)

ent: 0.8548387096774194 0.9814814814814815 0.9137931034482759
attr: 0.9067357512953368 0.9358288770053476 0.9210526315789473
unique: 1.0 0.9591836734693877 0.9791666666666666
composite: 0.8 1.0 0.888888888888889
multivalued: 0.2 1.0 0.33333333333333337
relation: 0.6491228070175439 0.74 0.6915887850467289
